vim9script

# Name:         default256
# Author:       Generated from Neovim default colorscheme
# Last Change:  2026 Feb 21

# Generated by Colortemplate v3.0.0-beta10

set background=dark

hi clear
g:colors_name = 'default256'

g:terminal_ansi_colors = ['#14161b', '#ffc0b9', '#b3f6c0', '#fce094', '#a6dbff', '#ffcaff', '#8cf8f7', '#e0e2ea', '#14161b', '#ffc0b9', '#b3f6c0', '#fce094', '#a6dbff', '#ffcaff', '#8cf8f7', '#e0e2ea']

hi! link Boolean Constant
hi! link Character Constant
hi! link ComplMatchIns NONE
hi! link Conditional Statement
hi! link CursorIM Cursor
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link DiffTextAdd DiffText
hi! link EndOfBuffer NonText
hi! link Exception Statement
hi! link Float Number
hi! link FoldColumn SignColumn
hi! link GitGutterAdd Added
hi! link GitGutterChange Changed
hi! link GitGutterChangeDelete Changed
hi! link GitGutterDelete Removed
hi! link Ignore Normal
hi! link IncSearch CurSearch
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MsgArea NONE
hi! link Number Constant
hi! link PmenuBorder Pmenu
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuSbar Pmenu
hi! link PreCondit PreProc
hi! link PreInsert Added
hi! link Quote String
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link SpecialKey Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link Structure Type
hi! link TabLine StatusLineNC
hi! link TabLineFill TabLine
hi! link Tag Special
hi! link Typedef Type
hi! link VertSplit Normal
hi! link VisualNOS Visual
hi! link WildMenu PmenuSel
hi! link asciidoctorBlock Special
hi! link asciidoctorCode String
hi! link asciidoctorH1Delimiter Statement
hi! link asciidoctorH2Delimiter Statement
hi! link asciidoctorH3Delimiter Statement
hi! link asciidoctorH4Delimiter Statement
hi! link asciidoctorH5Delimiter Statement
hi! link asciidoctorH6Delimiter Statement
hi! link asciidoctorListMarker Constant
hi! link asciidoctorMacro Special
hi! link asciidoctorOption Special
hi! link asciidoctorSetextHeaderDelimiter Statement
hi! link asciidoctorTitleDelimiter Statement
hi! link javaScriptFunction Statement
hi! link javaScriptIdentifier Statement
hi! link lspDiagSignErrorText Removed
hi! link lspDiagSignHintText Added
hi! link lspDiagSignInfoText Question
hi! link lspDiagSignWarningText Changed
hi! link lspDiagVirtualTextError Removed
hi! link lspDiagVirtualTextHint Added
hi! link lspDiagVirtualTextInfo Question
hi! link lspDiagVirtualTextWarning Changed
hi! link markdownUrl String
hi! link rubyDefine Statement
hi! link rubyMacro Statement
hi! link sqlKeyword Statement
hi! link sqlSpecial Constant
hi! link vimCommentString Comment
hi! link vimOper Normal
hi! link vimParenSep Normal
hi! link vimSep Normal
hi! link vimVar Normal
hi! link yamlBlockMappingKey Statement

hi Normal guifg=#e0e2ea guibg=#14161b guisp=NONE gui=NONE ctermfg=254 ctermbg=233 cterm=NONE
hi Added guifg=#b3f6c0 guibg=NONE guisp=NONE gui=NONE ctermfg=158 ctermbg=NONE cterm=NONE
hi Changed guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi ColorColumn guifg=NONE guibg=#4f5258 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi Comment guifg=#9b9ea4 guibg=NONE guisp=NONE gui=NONE ctermfg=247 ctermbg=NONE cterm=NONE
hi Conceal guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi Constant guifg=#e0e2ea guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
hi CurSearch guifg=#07080d guibg=#fce094 guisp=NONE gui=NONE ctermfg=232 ctermbg=222 cterm=NONE
hi Cursor guifg=bg guibg=fg guisp=NONE gui=NONE ctermfg=bg ctermbg=fg cterm=NONE
hi CursorColumn guifg=NONE guibg=#2c2e33 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
hi CursorLine guifg=NONE guibg=#2c2e33 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
hi CursorLineNr guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi Delimiter guifg=#e0e2ea guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
hi DiffAdd guifg=#eef1f8 guibg=#005523 guisp=NONE gui=NONE ctermfg=255 ctermbg=22 cterm=NONE
hi DiffChange guifg=#eef1f8 guibg=#4f5258 guisp=NONE gui=NONE ctermfg=255 ctermbg=239 cterm=NONE
hi DiffDelete guifg=#ffc0b9 guibg=NONE guisp=NONE gui=bold ctermfg=217 ctermbg=NONE cterm=bold
hi DiffText guifg=#eef1f8 guibg=#007373 guisp=NONE gui=NONE ctermfg=255 ctermbg=23 cterm=NONE
hi Directory guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi Error guifg=#eef1f8 guibg=#590008 guisp=NONE gui=NONE ctermfg=255 ctermbg=52 cterm=NONE
hi ErrorMsg guifg=#ffc0b9 guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi Folded guifg=#9b9ea4 guibg=#07080d guisp=NONE gui=NONE ctermfg=247 ctermbg=232 cterm=NONE
hi Function guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi Identifier guifg=#a6dbff guibg=NONE guisp=NONE gui=NONE ctermfg=153 ctermbg=NONE cterm=NONE
hi LineNr guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi MatchParen guifg=NONE guibg=#4f5258 guisp=NONE gui=bold ctermfg=NONE ctermbg=239 cterm=bold
hi ModeMsg guifg=#b3f6c0 guibg=NONE guisp=NONE gui=NONE ctermfg=158 ctermbg=NONE cterm=NONE
hi MoreMsg guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi NonText guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi Operator guifg=#e0e2ea guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
hi Pmenu guifg=NONE guibg=#2c2e33 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
hi PmenuMatch guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi PmenuMatchSel guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi PmenuSel guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi PmenuShadow guifg=NONE guibg=#4f5258 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi PmenuThumb guifg=NONE guibg=#4f5258 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi PreProc guifg=#e0e2ea guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
hi Question guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi QuickFixLine guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi Removed guifg=#ffc0b9 guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi Search guifg=#eef1f8 guibg=#6b5300 guisp=NONE gui=NONE ctermfg=255 ctermbg=94 cterm=NONE
hi SignColumn guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi Special guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#ffc0b9 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=217
hi SpellCap guifg=NONE guibg=NONE guisp=#fce094 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=222
hi SpellLocal guifg=NONE guibg=NONE guisp=#b3f6c0 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=158
hi SpellRare guifg=NONE guibg=NONE guisp=#8cf8f7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=123
hi Statement guifg=#e0e2ea guibg=NONE guisp=NONE gui=bold ctermfg=254 ctermbg=NONE cterm=bold
hi StatusLine guifg=#2c2e33 guibg=#c4c6cd guisp=NONE gui=NONE ctermfg=236 ctermbg=251 cterm=NONE
hi StatusLineNC guifg=#e0e2ea guibg=#4f5258 guisp=NONE gui=NONE ctermfg=254 ctermbg=239 cterm=NONE
hi String guifg=#b3f6c0 guibg=NONE guisp=NONE gui=NONE ctermfg=158 ctermbg=NONE cterm=NONE
hi TabLineSel guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi Title guifg=#e0e2ea guibg=NONE guisp=NONE gui=bold ctermfg=254 ctermbg=NONE cterm=bold
hi Todo guifg=#e0e2ea guibg=NONE guisp=NONE gui=bold ctermfg=254 ctermbg=NONE cterm=bold
hi Type guifg=#e0e2ea guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi Visual guifg=NONE guibg=#4f5258 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi WarningMsg guifg=#fce094 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi lCursor guifg=bg guibg=fg guisp=NONE gui=NONE ctermfg=bg ctermbg=fg cterm=NONE

# vim: et ts=8 sw=2 sts=2
