vim9script

# Name:         default256
# Author:       Generated from Neovim default colorscheme
# Last Change:  2025 Nov 11

# Generated by Colortemplate v3.0.0-beta10

set background=dark

hi clear
g:colors_name = 'default256'

const t_Co = has('gui_running') ? 16777216 : str2nr(&t_Co)
const tgc = has('termguicolors') && &termguicolors

g:terminal_ansi_colors = ['#14161b', '#ffc0b9', '#b3f6c0', '#fce094', '#a6dbff', '#e0e2ea', '#8cf8f7', '#9b9ea4', '#4f5258', '#ffc0b9', '#b3f6c0', '#fce094', '#a6dbff', '#e0e2ea', '#8cf8f7', '#e0e2ea']

hi! link Character Constant
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link EndOfBuffer NonText
hi! link Float Number
hi! link FoldColumn SignColumn
hi! link Ignore Normal
hi! link IncSearch CurSearch
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Number Constant
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuSbar Pmenu
hi! link Quote String
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link TabLine StatusLineNC
hi! link TabLineFill TabLine
hi! link VertSplit WinSeparator
hi! link VisualNOS Visual
hi! link WildMenu PmenuSel
hi! link WinSeparator Normal
hi! link asciidoctorBlock Special
hi! link asciidoctorCode String
hi! link asciidoctorH1Delimiter Statement
hi! link asciidoctorH2Delimiter Statement
hi! link asciidoctorH3Delimiter Statement
hi! link asciidoctorH4Delimiter Statement
hi! link asciidoctorH5Delimiter Statement
hi! link asciidoctorH6Delimiter Statement
hi! link asciidoctorListMarker Constant
hi! link asciidoctorMacro Special
hi! link asciidoctorOption Special
hi! link asciidoctorSetextHeaderDelimiter Statement
hi! link asciidoctorTitleDelimiter Statement
hi! link javaScriptFunction Statement
hi! link javaScriptIdentifier Statement
hi! link lspDiagSignErrorText Removed
hi! link lspDiagSignHintText Added
hi! link lspDiagSignInfoText Question
hi! link lspDiagSignWarningText Changed
hi! link lspDiagVirtualTextError Removed
hi! link lspDiagVirtualTextHint Added
hi! link lspDiagVirtualTextInfo Question
hi! link lspDiagVirtualTextWarning Changed
hi! link markdownUrl String
hi! link rubyDefine Statement
hi! link rubyMacro Statement
hi! link sqlKeyword Statement
hi! link sqlSpecial Constant
hi! link vimCommentString Comment
hi! link vimOper Normal
hi! link vimParenSep Normal
hi! link vimSep Normal
hi! link vimVar Normal
hi! link yamlBlockMappingKey Statement

hi Normal guifg=#e0e2ea guibg=#14161b guisp=NONE gui=NONE ctermfg=254 ctermbg=233 cterm=NONE
hi Added guifg=#b3f6c0 guibg=NONE guisp=NONE gui=NONE ctermfg=158 ctermbg=NONE cterm=NONE
hi Changed guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi ColorColumn guifg=NONE guibg=#4f5258 guisp=NONE gui=reverse ctermfg=NONE ctermbg=239 cterm=reverse
hi Comment guifg=#9b9ea4 guibg=NONE guisp=NONE gui=NONE ctermfg=247 ctermbg=NONE cterm=NONE
hi Conceal guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi Constant guifg=#e0e2ea guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
hi CurSearch guifg=#eef1f8 guibg=#6b5300 guisp=NONE gui=NONE ctermfg=255 ctermbg=94 cterm=NONE
hi Cursor guifg=#14161b guibg=#e0e2ea guisp=NONE gui=NONE ctermfg=233 ctermbg=254 cterm=NONE
hi CursorColumn guifg=NONE guibg=#2c2e33 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
hi CursorLine guifg=NONE guibg=#2c2e33 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
hi CursorLineNr guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi DiffAdd guifg=#eef1f8 guibg=#005523 guisp=NONE gui=NONE ctermfg=255 ctermbg=22 cterm=NONE
hi DiffChange guifg=#eef1f8 guibg=#4f5258 guisp=NONE gui=NONE ctermfg=255 ctermbg=239 cterm=NONE
hi DiffDelete guifg=#ffc0b9 guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi DiffText guifg=#eef1f8 guibg=#007373 guisp=NONE gui=NONE ctermfg=255 ctermbg=23 cterm=NONE
hi Directory guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi Error guifg=#eef1f8 guibg=#590008 guisp=NONE gui=NONE ctermfg=255 ctermbg=52 cterm=NONE
hi ErrorMsg guifg=#ffc0b9 guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi Folded guifg=#9b9ea4 guibg=#07080d guisp=NONE gui=NONE ctermfg=247 ctermbg=232 cterm=NONE
hi Function guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi Identifier guifg=#a6dbff guibg=NONE guisp=NONE gui=NONE ctermfg=153 ctermbg=NONE cterm=NONE
hi LineNr guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi MatchParen guifg=NONE guibg=#4f5258 guisp=NONE gui=bold ctermfg=NONE ctermbg=239 cterm=bold
hi ModeMsg guifg=#b3f6c0 guibg=NONE guisp=NONE gui=NONE ctermfg=158 ctermbg=NONE cterm=NONE
hi MoreMsg guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi NonText guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi Pmenu guifg=NONE guibg=#2c2e33 guisp=NONE gui=reverse ctermfg=NONE ctermbg=236 cterm=reverse
hi PmenuBorder guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi PmenuMatch guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi PmenuMatchSel guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi PmenuSel guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse,underline
hi PmenuShadow guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi PmenuThumb guifg=NONE guibg=#4f5258 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi PreProc guifg=#e0e2ea guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
hi Question guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi QuickFixLine guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi Removed guifg=#ffc0b9 guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi Search guifg=#eef1f8 guibg=#6b5300 guisp=NONE gui=NONE ctermfg=255 ctermbg=94 cterm=NONE
hi SignColumn guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi Special guifg=#8cf8f7 guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
hi SpecialKey guifg=#4f5258 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#ffc0b9 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=217
hi SpellCap guifg=NONE guibg=NONE guisp=#fce094 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=222
hi SpellLocal guifg=NONE guibg=NONE guisp=#b3f6c0 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=158
hi SpellRare guifg=NONE guibg=NONE guisp=#8cf8f7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=123
hi Statement guifg=#e0e2ea guibg=NONE guisp=NONE gui=bold ctermfg=254 ctermbg=NONE cterm=bold
hi StatusLine guifg=#2c2e33 guibg=#c4c6cd guisp=NONE gui=reverse ctermfg=236 ctermbg=251 cterm=reverse
hi StatusLineNC guifg=#e0e2ea guibg=#4f5258 guisp=NONE gui=NONE ctermfg=254 ctermbg=239 cterm=NONE
hi String guifg=#b3f6c0 guibg=NONE guisp=NONE gui=NONE ctermfg=158 ctermbg=NONE cterm=NONE
hi TabLineSel guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi Title guifg=#e0e2ea guibg=NONE guisp=NONE gui=bold ctermfg=254 ctermbg=NONE cterm=bold
hi TitleBar guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi TitleBarNC guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Todo guifg=#e0e2ea guibg=NONE guisp=NONE gui=bold ctermfg=254 ctermbg=NONE cterm=bold
hi ToolbarButton guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Type guifg=#e0e2ea guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi Visual guifg=NONE guibg=#4f5258 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi WarningMsg guifg=#fce094 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi debugBreakpoint guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi debugPC guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi lCursor guifg=#14161b guibg=#e0e2ea guisp=NONE gui=NONE ctermfg=233 ctermbg=254 cterm=NONE

if tgc || t_Co >= 256
  if tgc
    hi CurSearch cterm=NONE
    hi Error cterm=NONE
    hi QuickFixLine cterm=NONE
    hi Search cterm=NONE
    hi SpellBad guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=217
    hi SpellCap guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=222
    hi SpellLocal guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=158
    hi SpellRare guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE cterm=undercurl ctermul=123
    hi Visual cterm=NONE
  endif
  finish
endif

# vim: et ts=8 sw=2 sts=2
